# Generated by Django 5.0.1 on 2024-01-31 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gijutsu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeltColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=64)),
                ('martial_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gijutsu.martialart')),
            ],
        ),
        migrations.DeleteModel(
            name='BeltRanking',
        ),
    ]
