# Generated by Django 5.0.1 on 2024-01-31 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gijutsu', '0002_beltcolor_delete_beltranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeltRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belt_color', models.CharField(max_length=64)),
                ('martial_arts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gijutsu.martialart')),
                ('technique', models.ManyToManyField(related_name='belt_ranking', to='gijutsu.technique')),
            ],
        ),
    ]
